### PR TITLE
Add 4 new muzzle devices

### PR DESCRIPTION
**Pull request by Hyperseeker**
Adds 4 muzzle devices:

* [micro muzzle brake](https://yhm.net/q-d-muzzle-brakes/srx-mini-muzzle-brake/): very small, but surprisingly-effective
* [linear compensator](https://slrrifleworks.com/synergy-linear-hybrid-comp-5-56-223-1-2x28/): small handling bonus, removes loudness (IRL just redirects it, but we can't do "sound at muzzle vs. sound at ear")
* [hybrid muzzle brake](https://yhm.net/accessories/muzzle-accessories/5-56mm-slant-muzzle-brake-comp/): hybrid between a muzzle brake and a linear compensator, slightly weaker than heavy muzzle brake but much smaller and not as loud
* [barrel extension](https://dbtac.com/product/db-tac-inc-1-2x28-tpi-thread-7-inch-muzzle-brake-and-6-inch-aluminum-red-color-fake-can-slip-over-barrel-for-22-223-5-56-caliber/): suppressor-looking thing that gives 6 extra inches to the gun (translates into +2 damage), and also makes the gun slightly less loud as a bonus (longer barrels are quieter because powder has a chance to burn more fully)

Also edits heavy muzzle brake's `mod_targets` because I forgot how PRs work.

### CODE REVIEW

**Review by jackledead — COMMENTED** [review]
image

I'm curious if we could make the micro fit a pistol as well please? 

The others looks okay, you feel like you did a good job balancing them?

and have you run them in game?

**Comment by jackledead** [comment]
Also, could you please update the itemgroups to include these new mods?

**Comment by Hyperseeker** [comment]
> I'm curious if we could make the micro fit a pistol as well please?

Sure. The only reason I haven't is because the micro brake is IRL meant for a rifle.

> you feel like you did a good job balancing them?

I've relied entirely on the mod's existing balancing to make these items. Proportionally, they should be okay relative to other entries.

> and have you run them in game?

I haven't, but I have copied the existing entries. If the new ones don't work, it's because none of them do to begin with.

> Also, could you please update the itemgroups to include these new mods?

Sure thing. I was thinking I'd make it a separate PR, but I think keeping it contained is a good idea.

**Comment by jackledead** [comment]
> Sure. The only reason I haven't is because the micro brake is IRL meant for a rifle.
image


i mainly want it becasue i think making another muzzle break for pistols would be pointless, this item covers it well, and players wont be likely switching it very often from rifle to smg to pistol,

also it says 9mm and below which is what prompted the thought.

**Comment by Hyperseeker** [comment]
> also it says 9mm and below which is what prompted the thought.

...that would explain the size, yes. I should've read the source more-clearly.

Okay, the new devices should now spawn where they're appropriate. I've added all 4 to the `gunmod_*` groups, and 2 (linear compensator and hybrid muzzle brake) to the `military` group. (The other 2 it didn't make sense to include there.) I haven't tested the spawns manually, but again: all I did was add to the `extend` list; if the new ones don't spawn, it's because none of the modded ones can.

**Pull request merged**
